kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-agent-viewer-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: k8s-agent-viewer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io