---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-agent
  template:
    metadata:
      labels:
        app: k8s-agent
    spec:
      serviceAccountName: k8s-agent-viewer
      containers:
      - name: myapp
        image: coderpews/k8s-agent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>
